config/routes.rb
Rails.application.routes.draw do
  # mounting the grape api
  mount API::Base => "/"

  # resources & namespaces
  namespace :authentication do
    resources :locals
  end

  resources :shifts
  resources :rosters
  resources :users

  # welcome/statics
  get '/welcome/organisation', to: "welcome#index"
  root 'welcome#home'
  
  # Sessions
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
end

app/models/authentication.rb
module Authentication
  def self.table_name_prefix
    'authentication_'
  end
end

app/models/authentication/local.rb
class Authentication::Local < ApplicationRecord
  belongs_to :user
  has_secure_password
end

app/controllers/API/v1/authentications.rb
require 'jwt'

module API
  module V1
    class Authentications < Grape::API
     
      include API::V1::Defaults
      helpers do

        def authenticate!(email, password)
          @user_id = Authentication::Local.where(email: email)[0].user_id
          if User.authenticate(@user_id, password)
            @result = true
          else
            @result = false
          end
          return @result
        end

        def generate_jwt
          payload = { user: "some user details" }
          return JWT.encode payload, ENV["JWT_SECRET"], ENV['ALGORITHM']
        end
      end
      
      desc "authentications"
      namespace "authentication" do
        resource :locals do
          params do
            requires :email, type: String, desc: "User email"
            requires :password, type: String, desc: "User password"
          end
          post "" do
            if !!authenticate!(params[:email], params[:password])
              @token = generate_jwt
              status 200
              return { authentication_token: @token }
            else
              status 404
              error!({ error: "authentication failed" }, 401)
            end
          end
        end
      end
    end
  end
end

app/controllers/authentication/locals_controller.rb
class Authentication::LocalsController < ApplicationController

  before_action :set_authentication_local, only: [:show, :edit, :update, :destroy]
  before_action :logged_in_user, only: [:index, :show, :edit, :update, :destroy]

  def index
    @authentication_locals = Authentication::Local.all
  end

  def show
  end

  def new
    @authentication_local = Authentication::Local.new
  end

  def edit
  end

  def create
    @user = User.where(:email => params[:email])[0]

    if !@user
      @user = User.create(:email => authentication_local_params[:email])
    end

    @authentication_local_params = {:email => authentication_local_params[:email], :password_digest => User.hash_password(authentication_local_params[:password_digest])}
    @authentication_local_params[:user_id] = @user.id
    @authentication_local = Authentication::Local.new(@authentication_local_params)

    if @authentication_local.save
      redirect_to @authentication_local, notice: 'Local was successfully created.' 
    else
      render :new 
    end
  end

  def update
    @authentication_local_params = {:email => authentication_local_params[:email], :password_digest => User.hash_password(authentication_local_params[:password_digest])}
    if @authentication_local.update(@authentication_local_params)
      redirect_to @authentication_local, notice: 'Local was successfully updated.' 
    else
      render :edit
    end
  end

  def destroy
    @authentication_local.destroy
    redirect_to authentication_locals_url, notice: 'Local was successfully destroyed.' 
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_authentication_local
      @authentication_local = Authentication::Local.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def authentication_local_params
      params.require(:authentication_local).permit(:email, :password_digest, :password_confirmation, :user_id)
    end
end

app/helpers/authentication/locals_helper.rb
module Authentication::LocalsHelper
end

app/views/authentication/locals/_form.html.erb
<%= form_with(model: authentication_local, local: true) do |form| %>
  <% if authentication_local.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(authentication_local.errors.count, "error") %> prohibited this authentication_local from being saved:</h2>

      <ul>
        <% authentication_local.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label 'Password' %>
    <%= form.password_field :password_digest %>
  </div>

  <div class="field">
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/authentication/locals/edit.html.erb
<h1>Editing Authentication Local</h1>

<%= render 'form', authentication_local: @authentication_local %>

<%= link_to 'Show', @authentication_local %> |
<%= link_to 'Back', authentication_locals_path %>

app/views/authentication/locals/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Authentication Locals</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @authentication_locals.each do |authentication_local| %>
      <tr>
        <td><%= authentication_local.email %></td>
        <td><%= authentication_local.user_id %></td>
        <td><%= link_to 'Show', authentication_local %></td>
        <td><%= link_to 'Edit', edit_authentication_local_path(authentication_local) %></td>
        <td><%= link_to 'Destroy', authentication_local, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Authentication Local', new_authentication_local_path %>

app/views/authentication/locals/new.html.erb
<h1>New Authentication Local</h1>

<%= render 'form', authentication_local: @authentication_local %>

<%= link_to 'Back', authentication_locals_path %>
<%= link_to 'Use your twitter account instead' %>
<%= link_to 'Use your google account instead'%>

app/views/authentication/locals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @authentication_local.email %>
</p>

<p>
  <strong>User:</strong>
  <%= @authentication_local.user_id %>
</p>

<%= link_to 'Edit', edit_authentication_local_path(@authentication_local) %> |
<%= link_to 'Back', authentication_locals_path %>