config/routes.rb
Rails.application.routes.draw do
  # mounting the grape api
  mount API::Base => "/"

  # resources & namespaces
  namespace :authentication do
    resources :locals
  end

  resources :shifts
  resources :rosters
  resources :users

  # welcome/statics
  get '/welcome/organisation', to: "welcome#index"
  root 'welcome#home'
  
  # Sessions
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
end

app/models/roster.rb
class Roster < ApplicationRecord
  belongs_to :volunteer
  belongs_to :organisation
end

app/controllers/rosters_controller.rb
class RostersController < ApplicationController
  before_action :set_roster, only: [:show, :edit, :update, :destroy]

  # GET /rosters
  # GET /rosters.json
  def index
    @rosters = Roster.all
  end

  # GET /rosters/1
  # GET /rosters/1.json
  def show
  end

  # GET /rosters/new
  def new
    @roster = Roster.new
  end

  # GET /rosters/1/edit
  def edit
  end

  # POST /rosters
  # POST /rosters.json
  def create
    @roster = Roster.new(roster_params)

    respond_to do |format|
      if @roster.save
        format.html { redirect_to @roster, notice: 'Roster was successfully created.' }
        format.json { render :show, status: :created, location: @roster }
      else
        format.html { render :new }
        format.json { render json: @roster.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rosters/1
  # PATCH/PUT /rosters/1.json
  def update
    respond_to do |format|
      if @roster.update(roster_params)
        format.html { redirect_to @roster, notice: 'Roster was successfully updated.' }
        format.json { render :show, status: :ok, location: @roster }
      else
        format.html { render :edit }
        format.json { render json: @roster.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rosters/1
  # DELETE /rosters/1.json
  def destroy
    @roster.destroy
    respond_to do |format|
      format.html { redirect_to rosters_url, notice: 'Roster was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_roster
      @roster = Roster.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def roster_params
      params.require(:roster).permit(:title, :start_date, :finish_date, :volunteer_id, :organisation_id)
    end
end

app/helpers/rosters_helper.rb
module RostersHelper
end

app/views/rosters/_form.html.erb
<%= form_with(model: roster, local: true) do |form| %>
  <% if roster.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(roster.errors.count, "error") %> prohibited this roster from being saved:</h2>

      <ul>
        <% roster.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :start_date %>
    <%= form.date_select :start_date %>
  </div>

  <div class="field">
    <%= form.label :finish_date %>
    <%= form.date_select :finish_date %>
  </div>

  <div class="field">
    <%= form.label :volunteer_id %>
    <%= form.text_field :volunteer_id %>
  </div>

  <div class="field">
    <%= form.label :organisation_id %>
    <%= form.text_field :organisation_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/rosters/edit.html.erb
<h1>Editing Roster</h1>

<%= render 'form', roster: @roster %>

<%= link_to 'Show', @roster %> |
<%= link_to 'Back', rosters_path %>

app/views/rosters/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Rosters</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Start date</th>
      <th>Finish date</th>
      <th>Volunteer</th>
      <th>Organisation</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @rosters.each do |roster| %>
      <tr>
        <td><%= roster.title %></td>
        <td><%= roster.start_date %></td>
        <td><%= roster.finish_date %></td>
        <td><%= roster.volunteer_id %></td>
        <td><%= roster.organisation_id %></td>
        <td><%= link_to 'Show', roster %></td>
        <td><%= link_to 'Edit', edit_roster_path(roster) %></td>
        <td><%= link_to 'Destroy', roster, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Roster', new_roster_path %>

app/views/rosters/new.html.erb
<h1>New Roster</h1>

<%= render 'form', roster: @roster %>

<%= link_to 'Back', rosters_path %>

app/views/rosters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @roster.title %>
</p>

<p>
  <strong>Start date:</strong>
  <%= @roster.start_date %>
</p>

<p>
  <strong>Finish date:</strong>
  <%= @roster.finish_date %>
</p>

<p>
  <strong>Volunteer:</strong>
  <%= @roster.volunteer_id %>
</p>

<p>
  <strong>Organisation:</strong>
  <%= @roster.organisation_id %>
</p>

<%= link_to 'Edit', edit_roster_path(@roster) %> |
<%= link_to 'Back', rosters_path %>