config/routes.rb
Rails.application.routes.draw do
  # mounting the grape api
  mount API::Base => "/"

  # resources & namespaces
  namespace :authentication do
    resources :locals
  end

  resources :shifts
  resources :rosters
  resources :users

  # welcome/statics
  get '/welcome/organisation', to: "welcome#index"
  root 'welcome#home'
  
  # Sessions
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
end

app/models/shift.rb
class Shift < ApplicationRecord
  belongs_to :roster
end

app/controllers/shifts_controller.rb
class ShiftsController < ApplicationController
  before_action :set_shift, only: [:show, :edit, :update, :destroy]

  # GET /shifts
  # GET /shifts.json
  def index
    @shifts = Shift.all
  end

  # GET /shifts/1
  # GET /shifts/1.json
  def show
  end

  # GET /shifts/new
  def new
    @shift = Shift.new
  end

  # GET /shifts/1/edit
  def edit
  end

  # POST /shifts
  # POST /shifts.json
  def create
    @shift = Shift.new(shift_params)

    respond_to do |format|
      if @shift.save
        format.html { redirect_to @shift, notice: 'Shift was successfully created.' }
        format.json { render :show, status: :created, location: @shift }
      else
        format.html { render :new }
        format.json { render json: @shift.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /shifts/1
  # PATCH/PUT /shifts/1.json
  def update
    respond_to do |format|
      if @shift.update(shift_params)
        format.html { redirect_to @shift, notice: 'Shift was successfully updated.' }
        format.json { render :show, status: :ok, location: @shift }
      else
        format.html { render :edit }
        format.json { render json: @shift.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shifts/1
  # DELETE /shifts/1.json
  def destroy
    @shift.destroy
    respond_to do |format|
      format.html { redirect_to shifts_url, notice: 'Shift was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shift
      @shift = Shift.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def shift_params
      params.require(:shift).permit(:title, :date, :start_time, :finish_time, :roster_id, :location, :cancellation, :assigned_volunteers, :training_requirements, :description)
    end
end

app/helpers/shifts_helper.rb
module ShiftsHelper
end

app/views/shifts/_form.html.erb
<%= form_with(model: shift, local: true) do |form| %>
  <% if shift.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(shift.errors.count, "error") %> prohibited this shift from being saved:</h2>

      <ul>
        <% shift.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :date %>
    <%= form.date_select :date %>
  </div>

  <div class="field">
    <%= form.label :start_time %>
    <%= form.datetime_select :start_time %>
  </div>

  <div class="field">
    <%= form.label :finish_time %>
    <%= form.datetime_select :finish_time %>
  </div>

  <div class="field">
    <%= form.label :roster_id %>
    <%= form.text_field :roster_id %>
  </div>

  <div class="field">
    <%= form.label :location %>
    <%= form.text_field :location %>
  </div>

  <div class="field">
    <%= form.label :cancellation %>
    <%= form.check_box :cancellation %>
  </div>

  <div class="field">
    <%= form.label :assigned_volunteers %>
    <%= form.text_field :assigned_volunteers %>
  </div>

  <div class="field">
    <%= form.label :training_requirements %>
    <%= form.text_field :training_requirements %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/shifts/edit.html.erb
<h1>Editing Shift</h1>

<%= render 'form', shift: @shift %>

<%= link_to 'Show', @shift %> |
<%= link_to 'Back', shifts_path %>

app/views/shifts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Shifts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Date</th>
      <th>Start time</th>
      <th>Finish time</th>
      <th>Roster</th>
      <th>Location</th>
      <th>Cancellation</th>
      <th>Assigned volunteers</th>
      <th>Training requirements</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @shifts.each do |shift| %>
      <tr>
        <td><%= shift.title %></td>
        <td><%= shift.date %></td>
        <td><%= shift.start_time %></td>
        <td><%= shift.finish_time %></td>
        <td><%= shift.roster_id %></td>
        <td><%= shift.location %></td>
        <td><%= shift.cancellation %></td>
        <td><%= shift.assigned_volunteers %></td>
        <td><%= shift.training_requirements %></td>
        <td><%= shift.description %></td>
        <td><%= link_to 'Show', shift %></td>
        <td><%= link_to 'Edit', edit_shift_path(shift) %></td>
        <td><%= link_to 'Destroy', shift, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Shift', new_shift_path %>

app/views/shifts/new.html.erb
<h1>New Shift</h1>

<%= render 'form', shift: @shift %>

<%= link_to 'Back', shifts_path %>

app/views/shifts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @shift.title %>
</p>

<p>
  <strong>Date:</strong>
  <%= @shift.date %>
</p>

<p>
  <strong>Start time:</strong>
  <%= @shift.start_time %>
</p>

<p>
  <strong>Finish time:</strong>
  <%= @shift.finish_time %>
</p>

<p>
  <strong>Roster:</strong>
  <%= @shift.roster_id %>
</p>

<p>
  <strong>Location:</strong>
  <%= @shift.location %>
</p>

<p>
  <strong>Cancellation:</strong>
  <%= @shift.cancellation %>
</p>

<p>
  <strong>Assigned volunteers:</strong>
  <%= @shift.assigned_volunteers %>
</p>

<p>
  <strong>Training requirements:</strong>
  <%= @shift.training_requirements %>
</p>

<p>
  <strong>Description:</strong>
  <%= @shift.description %>
</p>

<%= link_to 'Edit', edit_shift_path(@shift) %> |
<%= link_to 'Back', shifts_path %>